export const LINEAR_SLEEP_THRESHOLD = 2;
export const ANGULAR_SLEEP_THRESHOLD = 0.05;
export const BIAS_LINEAR_SLEEP_THRESHOLD = 2;
export const BIAS_ANGULAR_SLEEP_THRESHOLD = 0.1;
export const SLEEP_TIME_THRESHOLD = 0.5;

export const SOLVER_ITERATIONS = 8;
export const CONTACT_BIAS = 0.8;
export const CONTACT_MAX_ALLOWED_PENETRATION = 0.1;
export const MAX_BIAS_VELOCITY = 120;
export const RESTITUTION_VELOCITY_THRESHOLD = 1;
export const CONTACT_SPEED_SLEEP_THRESHOLD = 2;
export const CONTACT_PENETRATION_SLEEP_THRESHOLD = 0.5;
export const SUPPORT_MIN_GRAVITY_DOT = 0.1;
